import Link from 'next/link'
import { SignUpButton } from '@clerk/nextjs'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

const steps = [
  {
    number: '01',
    title: 'Upload your garment',
    description: 'Upload a flat lay, mannequin, or hanger photo of your clothing item.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
      </svg>
    ),
  },
  {
    number: '02',
    title: 'Pick your model',
    description: 'Choose gender, skin tone, body type, pose, and background settings.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 6a3.75 3.75 0 11-7.5 0 3.75 3.75 0 017.5 0zM4.501 20.118a7.5 7.5 0 0114.998 0A17.933 17.933 0 0112 21.75c-2.676 0-5.216-.584-7.499-1.632z" />
      </svg>
    ),
  },
  {
    number: '03',
    title: 'Generate photos',
    description: 'Our AI generates 4 professional model photos wearing your garment.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
      </svg>
    ),
  },
  {
    number: '04',
    title: 'Download & publish',
    description: 'Download your photos individually or all at once, ready for your store.',
    icon: (
      <svg className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
        <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5M16.5 12L12 16.5m0 0L7.5 12m4.5 4.5V3" />
      </svg>
    ),
  },
]

const plans = [
  {
    name: 'Pay per use',
    price: '$1',
    unit: 'per generation',
    description: 'Perfect for testing or occasional use.',
    features: ['4 photos per generation', 'All model settings', 'HD downloads', 'No subscription'],
    cta: 'Get started',
    popular: false,
  },
  {
    name: 'Starter',
    price: '$19',
    unit: 'per month',
    description: 'For small brands and boutiques.',
    features: ['25 generations/month', 'All model settings', 'HD downloads', 'Generation history'],
    cta: 'Start free trial',
    popular: false,
  },
  {
    name: 'Pro',
    price: '$49',
    unit: 'per month',
    description: 'For growing fashion brands.',
    features: ['80 generations/month', 'All model settings', 'HD downloads', 'Priority processing', 'Generation history'],
    cta: 'Start free trial',
    popular: true,
  },
  {
    name: 'Agency',
    price: '$149',
    unit: 'per month',
    description: 'For agencies managing multiple brands.',
    features: ['300 generations/month', 'All model settings', 'HD downloads', 'Priority processing', 'Generation history', 'Dedicated support'],
    cta: 'Start free trial',
    popular: false,
  },
]

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />

      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="mx-auto max-w-6xl px-4 py-20 sm:px-6 sm:py-28 lg:py-36">
          <div className="mx-auto max-w-3xl text-center">
            <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-zinc-50 px-4 py-1.5 text-sm text-zinc-600">
              <span className="h-1.5 w-1.5 rounded-full bg-green-500"></span>
              No photoshoot required
            </div>
            <h1 className="mb-6 text-5xl font-bold leading-tight tracking-tight text-zinc-900 sm:text-6xl lg:text-7xl">
              Professional model photos,{' '}
              <span className="text-gradient">generated by AI</span>
            </h1>
            <p className="mb-10 text-xl leading-relaxed text-zinc-500 sm:text-2xl">
              Upload any clothing item and get 4 professional model photos in under 60 seconds.
              Replace expensive photoshoots with AI.
            </p>
            <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-center">
              <SignUpButton mode="modal">
                <button className="btn-primary px-8 py-3.5 text-base">
                  Generate photos free
                  <svg className="h-4 w-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M13.5 4.5L21 12m0 0l-7.5 7.5M21 12H3" />
                  </svg>
                </button>
              </SignUpButton>
              <p className="text-sm text-zinc-400">3 free generations. No credit card required.</p>
            </div>
          </div>

          {/* Hero image placeholder */}
          <div className="mt-16 rounded-3xl border border-zinc-100 bg-zinc-50 p-2 shadow-xl shadow-zinc-100">
            <div className="grid grid-cols-4 gap-3 rounded-2xl bg-white p-6">
              {/* Upload area */}
              <div className="col-span-1 flex flex-col items-center justify-center rounded-xl border-2 border-dashed border-zinc-200 bg-zinc-50 p-6 text-center">
                <div className="mb-3 flex h-10 w-10 items-center justify-center rounded-full bg-zinc-100">
                  <svg className="h-5 w-5 text-zinc-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                    <path strokeLinecap="round" strokeLinejoin="round" d="M3 16.5v2.25A2.25 2.25 0 005.25 21h13.5A2.25 2.25 0 0021 18.75V16.5m-13.5-9L12 3m0 0l4.5 4.5M12 3v13.5" />
                  </svg>
                </div>
                <p className="text-xs font-medium text-zinc-600">Your garment</p>
                <p className="mt-1 text-xs text-zinc-400">Upload photo</p>
              </div>

              {/* Generated images */}
              {[
                { bg: 'bg-zinc-100', label: 'Studio white' },
                { bg: 'bg-stone-100', label: 'Editorial' },
                { bg: 'bg-slate-100', label: 'Lifestyle' },
              ].map((item, i) => (
                <div key={i} className={`col-span-1 rounded-xl ${item.bg} aspect-[3/4] relative overflow-hidden`}>
                  <div className="absolute inset-0 flex flex-col items-center justify-end p-3">
                    <span className="rounded-full bg-white/90 px-2.5 py-0.5 text-xs font-medium text-zinc-700">
                      {item.label}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Social proof */}
      <section className="border-y border-zinc-100 bg-zinc-50 py-12">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="flex flex-wrap items-center justify-center gap-8 sm:gap-16">
            {['500+ brands', '50,000+ photos', '$2M+ saved', '4.9/5 rating'].map((stat) => (
              <div key={stat} className="text-center">
                <p className="text-2xl font-bold text-zinc-900">{stat.split(' ')[0]}</p>
                <p className="text-sm text-zinc-500">{stat.split(' ').slice(1).join(' ')}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="py-20 sm:py-28" id="how-it-works">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mb-16 text-center">
            <h2 className="mb-4 text-4xl font-bold text-zinc-900">How it works</h2>
            <p className="text-lg text-zinc-500">
              From clothing photo to professional model shoot in 4 simple steps.
            </p>
          </div>

          <div className="grid gap-8 sm:grid-cols-2 lg:grid-cols-4">
            {steps.map((step) => (
              <div key={step.number} className="relative">
                <div className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-zinc-900 text-white">
                  {step.icon}
                </div>
                <div className="absolute -top-2 left-12 text-4xl font-bold text-zinc-100">
                  {step.number}
                </div>
                <h3 className="mb-2 font-semibold text-zinc-900">{step.title}</h3>
                <p className="text-sm leading-relaxed text-zinc-500">{step.description}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-zinc-950 py-20 sm:py-28">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mb-16 text-center">
            <h2 className="mb-4 text-4xl font-bold text-white">Everything you need</h2>
            <p className="text-lg text-zinc-400">
              Powerful options to match your brand aesthetic perfectly.
            </p>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
            {[
              { title: 'Diverse model options', desc: 'Female, male, and gender-neutral models across all skin tones and body types.' },
              { title: 'Multiple pose styles', desc: 'Standing, casual, editorial, and lifestyle poses to match any brand vibe.' },
              { title: 'Custom backgrounds', desc: 'Studio white, gray, outdoor, and lifestyle settings for every use case.' },
              { title: '4 photos per generation', desc: 'Get variety with 4 unique shots from a single garment upload.' },
              { title: 'HD quality downloads', desc: 'High-resolution images ready for your website, social, or print.' },
              { title: 'Generation history', desc: 'Access all your past generations and regenerate with different settings.' },
            ].map((feature) => (
              <div key={feature.title} className="rounded-2xl border border-zinc-800 bg-zinc-900 p-6">
                <div className="mb-3 h-2 w-2 rounded-full bg-white"></div>
                <h3 className="mb-2 font-semibold text-white">{feature.title}</h3>
                <p className="text-sm leading-relaxed text-zinc-400">{feature.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Pricing */}
      <section className="py-20 sm:py-28" id="pricing">
        <div className="mx-auto max-w-6xl px-4 sm:px-6">
          <div className="mb-16 text-center">
            <h2 className="mb-4 text-4xl font-bold text-zinc-900">Simple pricing</h2>
            <p className="text-lg text-zinc-500">
              Start free, upgrade when you&apos;re ready.
            </p>
          </div>

          <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {plans.map((plan) => (
              <div
                key={plan.name}
                className={`relative rounded-2xl p-6 ${
                  plan.popular
                    ? 'border-2 border-zinc-900 bg-zinc-900 text-white'
                    : 'border border-zinc-200 bg-white'
                }`}
              >
                {plan.popular && (
                  <div className="absolute -top-3 left-1/2 -translate-x-1/2">
                    <span className="rounded-full bg-zinc-900 border border-zinc-700 px-3 py-1 text-xs font-medium text-white ring-2 ring-white">
                      Most popular
                    </span>
                  </div>
                )}
                <h3 className={`font-semibold ${plan.popular ? 'text-white' : 'text-zinc-900'}`}>
                  {plan.name}
                </h3>
                <div className="mt-2 flex items-baseline gap-1">
                  <span className={`text-3xl font-bold ${plan.popular ? 'text-white' : 'text-zinc-900'}`}>
                    {plan.price}
                  </span>
                  <span className={`text-sm ${plan.popular ? 'text-zinc-400' : 'text-zinc-500'}`}>
                    {plan.unit}
                  </span>
                </div>
                <p className={`mt-2 text-sm ${plan.popular ? 'text-zinc-400' : 'text-zinc-500'}`}>
                  {plan.description}
                </p>
                <ul className="mt-6 space-y-2.5">
                  {plan.features.map((f) => (
                    <li key={f} className="flex items-center gap-2 text-sm">
                      <svg
                        className={`h-4 w-4 flex-shrink-0 ${plan.popular ? 'text-zinc-300' : 'text-zinc-900'}`}
                        fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}
                      >
                        <path strokeLinecap="round" strokeLinejoin="round" d="M5 13l4 4L19 7" />
                      </svg>
                      <span className={plan.popular ? 'text-zinc-300' : 'text-zinc-600'}>{f}</span>
                    </li>
                  ))}
                </ul>
                <Link
                  href="/sign-up"
                  className={`mt-8 block w-full rounded-lg px-4 py-2.5 text-center text-sm font-medium transition-all ${
                    plan.popular
                      ? 'bg-white text-zinc-900 hover:bg-zinc-100'
                      : 'bg-zinc-900 text-white hover:bg-zinc-700'
                  }`}
                >
                  {plan.cta}
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="border-t border-zinc-100 py-20 sm:py-28">
        <div className="mx-auto max-w-3xl px-4 text-center sm:px-6">
          <h2 className="mb-4 text-4xl font-bold text-zinc-900 sm:text-5xl">
            Start generating today
          </h2>
          <p className="mb-10 text-xl text-zinc-500">
            Join hundreds of fashion brands saving thousands on photography.
            3 free generations — no credit card needed.
          </p>
          <SignUpButton mode="modal">
            <button className="btn-primary px-10 py-4 text-base">
              Try RunwaySnap free
            </button>
          </SignUpButton>
        </div>
      </section>

      <Footer />
    </div>
  )
}
